"""
API keys:
    Store all the API keys.
"""


# SET HUOBI KEY
HUOBI_ACCESS_KEY = HUOBI_ACCESS_KEY_ANYIP
HUOBI_SECRET_KEY = HUOBI_SECRET_KEY_ANYIP

# SET POLONIEX KEY
POLONIEX_ACCESS_KEY = POLONIEX_ACCESS_KEY_ANYIP
POLONIEX_SECRET_KEY = POLONIEX_SECRET_KEY_ANYIP